name: VD Hourly Whatsapp

on:
  schedule:
    - cron: None
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json

      - run: python VD_Hourly_Whatsapp.py
        env:
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          UPLOAD_PRESET: ${{ secrets.UPLOAD_PRESET }}
          AISENSY_API_KEY: ${{ secrets.AISENSY_API_KEY }}
          AISENSY_CAMPAIGN_NAME: ${{ secrets.AISENSY_CAMPAIGN_NAME }}
          DESTINATIONS: ${{ secrets.VD_DESTINATIONS }}
          SHEET_ID: ${{ secrets.VD_SHEET_ID }}
